name: nebula
version: v1.9.6

summary: A scalable overlay networking tool.

description: |
  Nebula is a scalable overlay networking tool with a focus on performance, simplicity and security.
  It lets you seamlessly connect computers anywhere in the world. Nebula is portable, and runs on Linux, OSX, and Windows.
  (Also: keep this quiet, but we have an early prototype running on iOS).
  It can be used to connect a small number of computers, but is also able to connect tens of thousands of computers.

  Nebula incorporates a number of existing concepts like encryption, security groups, certificates,
  and tunneling, and each of those individual pieces existed before Nebula in various forms.
  What makes Nebula different to existing offerings is that it brings all of these ideas together,
  resulting in a sum that is greater than its individual parts.

  More info on Nebula https://github.com/slackhq/nebula

  For issues and other matters on this snap https://github.com/jwallden/nebula-snap

grade: stable
confinement: strict

base: core24

parts:
  nebula:
    plugin: go
    source: https://github.com/slackhq/nebula.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-type: git
    build-snaps:
      - go/latest/stable
    build-packages:
      - gcc

plugs:
  etc-nebula:
    interface: system-files
    read:
      - /etc/nebula
    write:
      - /etc/nebula

apps:
  nebula:
    command: bin/nebula
    plugs:
      - network
      - network-control
      - etc-nebula

  nebula-cert:
    command: bin/nebula-cert
    plugs:
      - etc-nebula

  run:
    command: bin/nebula -config $SNAP_COMMON/config/config.yaml
    plugs:
      - network
      - network-control

  daemon:
    command: bin/nebula -config $SNAP_COMMON/config/config.yaml
    daemon: simple
    plugs:
      - network
      - network-control

layout:
  /etc/nebula:
    bind: $SNAP_COMMON
